[package]
authors = ["Paul Min"]
name = "deserialize-lines"
description = "read from file or string and parse as JSON lines"
edition = "2024"
license = "MIT"
repository = "https://github.com/paulusminus/json-lines"
version = "0.1.0"

[dependencies]
futures-util = "0.3.34"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1", features = ["fs"] }
tokio-stream = { version = "0.1.19", features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
