[package]
authors = ["Paul Min"]
name = "deserialize-lines"
description = "read from file or string and parse as JSON lines"
edition = "2024"
license = "MIT"
repository = "https://github.com/paulusminus/deserialize-lines"
version = "0.3.0"

[dependencies]
futures-util = { version = "0.3.34", features = ["io"] }
pin-project = "1.1.13"

[dev-dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1", features = ["full"] }
