name: Publish on crates.io

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-slim
    steps:
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy,rustfmt
    - uses: actions/checkout@v7
    - name: Build
      run: cargo publish
